### ISSUE TITLE
[Issue/Bug] Fabric server 1.19.2, Wither Skull or Create goggles with Stardust/Ender Netherite cause issue.

### ISSUE THREAD

**Issue by Arthex1** [aleganza/Plenty-Of-Armor#4] opened 2023-03-21 19:00 UTC
Hello, there.

I play on a server which runs fabric 1.19.2 with create, and a bunch of other mods. One issue I have faced is that, whenever I try to wear a wither head, or goggles with other pieces of stardust/ender netherite  armour(leggings, chest plate, boots) I get a Internal server error. With the console saying it is unable to evaluate the effects of the armour. It works just as fine with elytra, however. If I clear the wither head or goggles, it works just as fine.

That's all, thank you!

**Comment by aleganza** [comment] 2023-03-21 20:34
Hello.

I think the issue is about the full-armor check algorithm, I'll try to fix it as soon as possible (I hope tomorrow), thank you for discovering this bug!
If meanwhile you can't play minecraft due to this error, try to put on your wither head/goggles without any of the other stardusite pieces, it will fix it momentarily.

**Comment by aleganza** [comment] 2023-03-26 16:49
Hello, the bug should be fixed. If you want to try the new version you can find it con curseforge, thanks for the help.
If another bug occurs with the create helmet, let me know under this issue, I will leave it open for around a week.

**Comment by Arthex1** [comment] 2023-03-31 05:51
Hello there, Apologies for replying late.

I just checked, and the issue seems to have been resolved, both with create and vanilla minecraft items. So, you may close the issue now. Thank you!

**Comment by aleganza** [comment] 2023-03-31 09:07
Don't worry, enjoy the mod!

**Closed as completed** 2023-03-31 09:08 UTC
